const WRONG_KEY='middleHomeEconomicsWrong',BEST_KEY='periodicTestBest:'+SUBJECT_ID;
let queue=[],pos=0,ok=0,answered=false,sessionWrong=new Set(),sessionCat={};
const $=id=>document.getElementById(id);
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function wrongSet(){try{return new Set(JSON.parse(localStorage.getItem(WRONG_KEY)||'[]'))}catch{return new Set()}}
function saveWrong(s){localStorage.setItem(WRONG_KEY,JSON.stringify([...s]))}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderModes(){$('modeGrid').innerHTML=MODES.map((m,i)=>`<button class="mode" data-mode-index="${i}"><div class="thumb">${art(m.ill)}</div><div class="ico">${m.ico}</div><h3>${m.title}</h3><p>${m.desc}</p></button>`).join('');document.querySelectorAll('[data-mode-index]').forEach(b=>b.onclick=()=>startMode(MODES[Number(b.dataset.modeIndex)].id))}
function screens(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function showHome(){screens('home');readBest();renderModes();window.scrollTo({top:0,behavior:'smooth'})}
function startMode(m){let base;if(m==='final')base=shuffle(Q).slice(0,50);else if(m==='quick')base=shuffle(Q).slice(0,10);else if(m==='wrong'){const ws=wrongSet();base=shuffle(Q.filter(q=>ws.has(q.id)));if(!base.length){alert('まだ間違い問題がないぞ！ 先に本番か単元練習をやろう。');return}}else base=shuffle(Q.filter(q=>q.cat===m));queue=base;pos=0;ok=0;answered=false;sessionWrong=new Set();sessionCat={};screens('quiz');renderQuestion();window.scrollTo(0,0)}
function renderQuestion(){if(pos>=queue.length){finish();return}answered=false;const q=queue[pos];$('catTag').textContent=q.cat;$('qNo').textContent=`${pos+1} / ${queue.length}`;$('bar').style.width=`${pos/queue.length*100}%`;$('ill').innerHTML=art(q.ill)+'<span class="illCap">挿し絵</span>';$('question').textContent=q.ask;$('feedback').className='feedback';$('feedback').textContent='';$('nextBtn').style.display='none';const opts=shuffle([q.answer,...q.wrong]);$('choices').innerHTML=opts.map((x,i)=>`<button class="choice"><span class="letter">${'ABCD'[i]}</span><span>${escapeHtml(x)}</span></button>`).join('');$('choices').querySelectorAll('.choice').forEach((b,i)=>b.onclick=()=>answer(b,opts[i]));updateStats()}
function answer(btn,val){if(answered)return;answered=true;const q=queue[pos],good=val===q.answer;sessionCat[q.cat]??={ok:0,total:0};sessionCat[q.cat].total++;const ws=wrongSet();document.querySelectorAll('.choice').forEach((b,i)=>{b.disabled=true;const t=b.querySelector('span:last-child').textContent;if(t===q.answer)b.classList.add('correct')});if(good){ok++;sessionCat[q.cat].ok++;ws.delete(q.id);burst();$('feedback').className='feedback show ok';$('feedback').innerHTML=`✅ 正解！ <b>${escapeHtml(q.answer)}</b><br>${escapeHtml(q.ex)}`}else{btn.classList.add('wrong');ws.add(q.id);sessionWrong.add(q.id);$('feedback').className='feedback show ng';$('feedback').innerHTML=`❌ 正解は <b>${escapeHtml(q.answer)}</b><br>${escapeHtml(q.ex)}`}saveWrong(ws);$('nextBtn').style.display='inline-flex';updateStats()}
function nextQuestion(){if(!answered)return;pos++;renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}
function updateStats(){const done=pos+(answered?1:0),rate=done?Math.round(ok/done*100):0;$('stDone').textContent=done;$('stOk').textContent=ok;$('stRate').textContent=rate+'%';const ws=wrongSet();$('stWrong').textContent=ws.size;const arr=[...ws].slice(-18).reverse();$('wrongList').innerHTML=arr.length?arr.map(id=>{const q=Q.find(x=>x.id===id);return q?`<div class="wrongItem"><b>${escapeHtml(q.cat)}</b><br>${escapeHtml(q.ask)}</div>`:''}).join(''):'<div class="wrongItem">まだ弱点なし。いい感じ。</div>'}
function finish(){const total=queue.length,score=total?Math.round(ok/total*100):0;screens('result');$('resultScore').textContent=score+'点';$('grade').textContent=score>=90?'S：期末いける🔥':score>=80?'A：かなり強い':score>=70?'B：あと一段':score>=60?'C：弱点を潰そう':'D：単元練習からやり直し';$('resultText').textContent=`${total}問中 ${ok}問正解。今回の間違い ${sessionWrong.size}問。`;$('breakdown').innerHTML=CATS.map(c=>{const x=sessionCat[c]||{ok:0,total:0};return `<div class="breakItem">${c}<b>${x.total?Math.round(x.ok/x.total*100):'--'}%</b><br><span style="color:var(--muted);font-size:12px">${x.ok}/${x.total}</span></div>`}).join('');saveBest(score);window.scrollTo({top:0,behavior:'smooth'})}
function burst(){for(let i=0;i<10;i++){const e=document.createElement('div');e.className='spark';e.textContent=['✨','🍱','★','🥕'][i%4];e.style.left=(45+Math.random()*10)+'vw';e.style.top=(34+Math.random()*12)+'vh';e.style.setProperty('--dx',(Math.random()*220-110)+'px');e.style.setProperty('--dy',(Math.random()*-170-30)+'px');document.body.appendChild(e);setTimeout(()=>e.remove(),760)}}
async function fb(){if(!window.GAKUSHU_FIREBASE_CONFIG)return null;try{const[a,d]=await Promise.all([import('https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.0.2/firebase-database.js')]);const app=a.getApps().length?a.getApps()[0]:a.initializeApp(window.GAKUSHU_FIREBASE_CONFIG);return{db:d.getDatabase(app),...d}}catch(e){console.warn(e);return null}}
async function readBest(){let b=Number(localStorage.getItem(BEST_KEY));if(!Number.isFinite(b))b=null;$('bestScore').textContent=b==null?'--':b;const f=await fb();if(!f){$('fbState').textContent='端末保存';return}try{const snap=await f.get(f.ref(f.db,'scoreUsers/gakushu-main/subjects/'+SUBJECT_ID));const v=snap.exists()?snap.val():null;if(v&&typeof v.best==='number'){b=b==null?v.best:Math.max(b,v.best);localStorage.setItem(BEST_KEY,String(b));$('bestScore').textContent=b}$('fbState').textContent='Firebase 同期ON'}catch(e){$('fbState').textContent='端末保存'}}
async function saveBest(score){let old=Number(localStorage.getItem(BEST_KEY));if(!Number.isFinite(old)||score>old){old=score;localStorage.setItem(BEST_KEY,String(score))}$('bestScore').textContent=old;const f=await fb();if(!f)return;try{const p=f.ref(f.db,'scoreUsers/gakushu-main/subjects/'+SUBJECT_ID),snap=await f.get(p),v=snap.exists()?snap.val():null,b=v&&typeof v.best==='number'?Math.max(v.best,score):score;await f.set(p,{...(v||{}),best:b,lastScore:score,subjectId:SUBJECT_ID,subjectName:SUBJECT_NAME,scoreUserId:'gakushu-main',updatedAt:f.serverTimestamp()});$('fbState').textContent='Firebase 同期済'}catch(e){console.warn(e)}}
renderModes();readBest();
