name = "mine-server-git2"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = true
preview_urls = true

[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
